export const GET_TASKS_COUNT = "GET_TASKS_COUNT";
export const GET_PAGE_TASKS = "GET_PAGE_TASKS";
export const SET_PAGE = "SET_PAGE";
export const SET_SORT_FILED = "SET_SORT_FILED";
export const SET_SORT_DIRECTION = "SET_SORT_DIRECTION";
export const RESET_STORE_TASKS = "RESET_STORE_TASKS";
